export const LOGIN = "login";
export const COMMON = "common";
export const CANDIDATES = "candidates";

export const sagaActions = {
  GET_RANDOM_DATA: "GET_RANDOM_DATA",
  GET_LOGIN_DATA: "GET_LOGIN_DATA",
  LOGIN_SAGA_FAILED: "LOGIN_SAGA_FAILED",
  SEND_MEDIA_SAGA: "SEND_MEDIA_SAGA",
  GET_ALL_CANDIDATES:"GET_ALL_CANDIDATES",
  GET_CANDIDATE_FILTER:"GET_CANDIDATE_FILTER",
  DATA_AFTER_FILTERING:"DATA_AFTER_FILTERING"
};
