export const LOGIN = "login";
export const COMMON = "common";
export const CANDIDATES = "candidates";
export const TECH_STACK = "techstack";
export const RECRUITERS = "recruiters";

export const sagaActions = {
  GET_RANDOM_DATA: "GET_RANDOM_DATA",
  GET_LOGIN_DATA: "GET_LOGIN_DATA",
  LOGIN_SAGA_FAILED: "LOGIN_SAGA_FAILED",
  SEND_MEDIA_SAGA: "SEND_MEDIA_SAGA",
  GET_ALL_CANDIDATES: "GET_ALL_CANDIDATES",
  GET_CANDIDATE_FILTER: "GET_CANDIDATE_FILTER",
  DATA_AFTER_FILTERING: "DATA_AFTER_FILTERING",
  GET_TECH_STACKS: "GET_TECH_STACKS",
  TECH_STACK_SAGA_FAILED: "TECH_STACK_SAGA_FAILED",
  SEARCH_TECH_STACK: "SEARCH_TECH_STACK",
  GET_RECRUITERS: "GET_RECRUITERS",
  RECRUITER_SAGA_FAILED: "RECRUITER_SAGA_FAILED",
  SEARCH_RECRUITER: "SEARCH_RECRUITER",
  UPDATE_RECRUITER: "UPDATE_RECRUITER",
  FETCH_ROLE: "FETCH_ROLE",
  GET_USER_DETAILS: "GET_USER_DETAILS",
};
