const Images = {
  loaderSpinner: require("./loader.svg").default,
  close: require("./close.svg").default,
  arrowUp: require("./arrowUp.svg").default,
  arrowDown: require("./arrowDown.svg").default,
  checkboxIdeal: require("./checkboxIdeal.svg").default,
  checked: require("./checked.svg").default,
  search: require("./search.svg").default,
  googleIcon: require("./googleIcon.svg").default,
  coditasIcon: require("./coditasIcon.svg").default,
  profileIcon: require("./profile.svg").default,
  notificationIcon: require("./bell.svg").default,
  deliveredIcon: require("./delivered.svg").default,
  readIcon: require("./read.svg").default,
  sentIcon: require("./sent.svg").default,
  plusIcon: require("./plus.svg").default,
  filterIcon: require("./filter.svg").default,
  noCandidates: require("./noCandidates.svg").default,
  sendIcon: require("./send.svg").default,
  templateIcon: require("./template.svg").default,
  attachmentIcon: require("./attachment.svg").default,
  tooltipIcon: require("./tooltipTip.svg").default,
  logoutIcon: require("./logout.svg").default,
  crossIcon: require("./cross.svg").default,
  rectangle: require("../images/rectangle.svg").default,
  docsAttachmentIcon: require("./docs.svg").default,
  imageAttachmentIcon: require("./gallery.svg").default,
  errorIcon: require("./error.svg").default,
  crossIconBlack: require("./crossIcon.svg").default,
  rightChevron: require("./rightChevron.svg").default,
  emptyStateImage: require("./emptyStateImg.svg").default,
  upArrowDisabled: require("./upArrowDisabled.svg").default,
  upArrowEnabled: require("./upArrowEnabled.svg").default,
  downArrowDisabled: require("./downArrowDisabled.svg").default,
  downArrowEnabled: require("./downArrowEnabled.svg").default,
  searchIcon:require("./searchIcon.svg").default,
  rightArrow:require("./rightArrow.svg").default,
  addButton:require("./addButton.svg").default,
  candidateEmptyState:require("./candidateEmptyState.svg").default,
}

export default Images;
